import os
from datetime import datetime
from typing import Dict

class ReportEngine:
    def __init__(self):
        self.reports_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "..", "..", "docs"))
        os.makedirs(self.reports_dir, exist_ok=True)

    def generate_markdown_report(self, benchmark_data: Dict) -> str:
        dataset = benchmark_data.get("dataset")
        samples = benchmark_data.get("samples")
        results = benchmark_data.get("results", [])
        
        # Sort by MAE
        results.sort(key=lambda x: x["mae"])
        best_model = results[0]["model_name"] if results else "None"
        
        md = f"""# AI Localization Research Report

**Date Generated**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Dataset**: {dataset}
**Total Samples Evaluated**: {samples}
**Best Performing Model**: {best_model}

## Benchmark Results

| Model Name | Algorithm | MAE (m) | RMSE (m) | Avg Inference Time (ms) |
|------------|-----------|---------|----------|-------------------------|

## Conclusion
This report was automatically generated by the SignalSense Enterprise AI Localization Studio.
"""
        filename = f"Report_{datetime.now().strftime('%Y%m%d%H%M')}.md"
        filepath = os.path.join(self.reports_dir, filename)
        
        with open(filepath, 'w') as f:
            f.write(md)
            
        return filepath

report_engine = ReportEngine()

def get_report_engine() -> ReportEngine:
    return report_engine
