"""Add missing tables and columns

Revision ID: 23b73b4fc6ef
Revises: 6456bbb5830d
Create Date: 2026-07-21 17:36:20.968127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23b73b4fc6ef'
down_revision: Union[str, Sequence[str], None] = '6456bbb5830d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aggregation_checkpoints',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('resolution', sa.String(), nullable=True),
    sa.Column('metric_name', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('last_aggregated_timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aggregation_checkpoints_entity_id'), 'aggregation_checkpoints', ['entity_id'], unique=False)
    op.create_index(op.f('ix_aggregation_checkpoints_metric_name'), 'aggregation_checkpoints', ['metric_name'], unique=False)
    op.create_index(op.f('ix_aggregation_checkpoints_resolution'), 'aggregation_checkpoints', ['resolution'], unique=False)
    op.create_table('discovery_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('total_scans', sa.Integer(), nullable=True),
    sa.Column('successful_scans', sa.Integer(), nullable=True),
    sa.Column('failed_scans', sa.Integer(), nullable=True),
    sa.Column('avg_scan_duration_ms', sa.Float(), nullable=True),
    sa.Column('max_scan_duration_ms', sa.Float(), nullable=True),
    sa.Column('reconnect_count', sa.Integer(), nullable=True),
    sa.Column('dropped_events', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discovery_statistics_id'), 'discovery_statistics', ['id'], unique=False)
    op.create_index(op.f('ix_discovery_statistics_timestamp'), 'discovery_statistics', ['timestamp'], unique=False)
    op.create_table('network_topology_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('node_count', sa.Integer(), nullable=True),
    sa.Column('edge_count', sa.Integer(), nullable=True),
    sa.Column('health_score', sa.Float(), nullable=True),
    sa.Column('is_compressed', sa.Boolean(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('topology_data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_network_topology_snapshots_id'), 'network_topology_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_network_topology_snapshots_timestamp'), 'network_topology_snapshots', ['timestamp'], unique=False)
    op.create_table('router_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('cpu_usage', sa.Float(), nullable=True),
    sa.Column('memory_usage', sa.Float(), nullable=True),
    sa.Column('uptime', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_router_status_history_id'), 'router_status_history', ['id'], unique=False)
    op.create_index(op.f('ix_router_status_history_timestamp'), 'router_status_history', ['timestamp'], unique=False)
    op.create_table('time_series_aggregates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('resolution', sa.String(), nullable=True),
    sa.Column('metric_name', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('avg_value', sa.Float(), nullable=True),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.Column('sum_value', sa.Float(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_series_aggregates_entity_id'), 'time_series_aggregates', ['entity_id'], unique=False)
    op.create_index(op.f('ix_time_series_aggregates_id'), 'time_series_aggregates', ['id'], unique=False)
    op.create_index(op.f('ix_time_series_aggregates_metric_name'), 'time_series_aggregates', ['metric_name'], unique=False)
    op.create_index(op.f('ix_time_series_aggregates_resolution'), 'time_series_aggregates', ['resolution'], unique=False)
    op.create_index(op.f('ix_time_series_aggregates_timestamp'), 'time_series_aggregates', ['timestamp'], unique=False)
    op.create_table('trend_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('time_window', sa.String(), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('previous_value', sa.Float(), nullable=True),
    sa.Column('growth_rate', sa.Float(), nullable=True),
    sa.Column('variance', sa.Float(), nullable=True),
    sa.Column('std_dev', sa.Float(), nullable=True),
    sa.Column('forecast_value', sa.Float(), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('last_calculated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trend_profiles_entity_id'), 'trend_profiles', ['entity_id'], unique=False)
    op.create_index(op.f('ix_trend_profiles_metric_name'), 'trend_profiles', ['metric_name'], unique=False)
    op.create_index(op.f('ix_trend_profiles_time_window'), 'trend_profiles', ['time_window'], unique=False)
    op.create_table('device_metadata_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('mac_address', sa.String(), nullable=True),
    sa.Column('field_name', sa.String(), nullable=True),
    sa.Column('old_value', sa.String(), nullable=True),
    sa.Column('new_value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['mac_address'], ['devices.mac_address'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_metadata_history_field_name'), 'device_metadata_history', ['field_name'], unique=False)
    op.create_index(op.f('ix_device_metadata_history_id'), 'device_metadata_history', ['id'], unique=False)
    op.create_index(op.f('ix_device_metadata_history_mac_address'), 'device_metadata_history', ['mac_address'], unique=False)
    op.create_index(op.f('ix_device_metadata_history_timestamp'), 'device_metadata_history', ['timestamp'], unique=False)
    op.add_column('events', sa.Column('entity_id', sa.String(), nullable=True))
    op.add_column('events', sa.Column('severity', sa.String(), nullable=True))
    op.add_column('events', sa.Column('category', sa.String(), nullable=True))
    op.add_column('events', sa.Column('source_module', sa.String(), nullable=True))
    op.add_column('events', sa.Column('correlation_id', sa.String(), nullable=True))
    op.add_column('events', sa.Column('search_tags', sa.String(), nullable=True))
    op.create_index(op.f('ix_events_category'), 'events', ['category'], unique=False)
    op.create_index(op.f('ix_events_correlation_id'), 'events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_events_entity_id'), 'events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_events_search_tags'), 'events', ['search_tags'], unique=False)
    op.create_index(op.f('ix_events_severity'), 'events', ['severity'], unique=False)
    op.create_index(op.f('ix_events_source_module'), 'events', ['source_module'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_source_module'), table_name='events')
    op.drop_index(op.f('ix_events_severity'), table_name='events')
    op.drop_index(op.f('ix_events_search_tags'), table_name='events')
    op.drop_index(op.f('ix_events_entity_id'), table_name='events')
    op.drop_index(op.f('ix_events_correlation_id'), table_name='events')
    op.drop_index(op.f('ix_events_category'), table_name='events')
    op.drop_column('events', 'search_tags')
    op.drop_column('events', 'correlation_id')
    op.drop_column('events', 'source_module')
    op.drop_column('events', 'category')
    op.drop_column('events', 'severity')
    op.drop_column('events', 'entity_id')
    op.drop_index(op.f('ix_device_metadata_history_timestamp'), table_name='device_metadata_history')
    op.drop_index(op.f('ix_device_metadata_history_mac_address'), table_name='device_metadata_history')
    op.drop_index(op.f('ix_device_metadata_history_id'), table_name='device_metadata_history')
    op.drop_index(op.f('ix_device_metadata_history_field_name'), table_name='device_metadata_history')
    op.drop_table('device_metadata_history')
    op.drop_index(op.f('ix_trend_profiles_time_window'), table_name='trend_profiles')
    op.drop_index(op.f('ix_trend_profiles_metric_name'), table_name='trend_profiles')
    op.drop_index(op.f('ix_trend_profiles_entity_id'), table_name='trend_profiles')
    op.drop_table('trend_profiles')
    op.drop_index(op.f('ix_time_series_aggregates_timestamp'), table_name='time_series_aggregates')
    op.drop_index(op.f('ix_time_series_aggregates_resolution'), table_name='time_series_aggregates')
    op.drop_index(op.f('ix_time_series_aggregates_metric_name'), table_name='time_series_aggregates')
    op.drop_index(op.f('ix_time_series_aggregates_id'), table_name='time_series_aggregates')
    op.drop_index(op.f('ix_time_series_aggregates_entity_id'), table_name='time_series_aggregates')
    op.drop_table('time_series_aggregates')
    op.drop_index(op.f('ix_router_status_history_timestamp'), table_name='router_status_history')
    op.drop_index(op.f('ix_router_status_history_id'), table_name='router_status_history')
    op.drop_table('router_status_history')
    op.drop_index(op.f('ix_network_topology_snapshots_timestamp'), table_name='network_topology_snapshots')
    op.drop_index(op.f('ix_network_topology_snapshots_id'), table_name='network_topology_snapshots')
    op.drop_table('network_topology_snapshots')
    op.drop_index(op.f('ix_discovery_statistics_timestamp'), table_name='discovery_statistics')
    op.drop_index(op.f('ix_discovery_statistics_id'), table_name='discovery_statistics')
    op.drop_table('discovery_statistics')
    op.drop_index(op.f('ix_aggregation_checkpoints_resolution'), table_name='aggregation_checkpoints')
    op.drop_index(op.f('ix_aggregation_checkpoints_metric_name'), table_name='aggregation_checkpoints')
    op.drop_index(op.f('ix_aggregation_checkpoints_entity_id'), table_name='aggregation_checkpoints')
    op.drop_table('aggregation_checkpoints')
    # ### end Alembic commands ###
