"""Initial migration

Revision ID: 6456bbb5830d
Revises: 
Create Date: 2026-07-18 17:22:44.454521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6456bbb5830d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('alert_type', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_alert_type'), 'alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_timestamp'), 'alerts', ['timestamp'], unique=False)
    op.create_table('devices',
    sa.Column('mac_address', sa.String(), nullable=False),
    sa.Column('hostname', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('device_type', sa.String(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('current_status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('mac_address')
    )
    op.create_index(op.f('ix_devices_mac_address'), 'devices', ['mac_address'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('mac_address', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_mac_address'), 'events', ['mac_address'], unique=False)
    op.create_index(op.f('ix_events_timestamp'), 'events', ['timestamp'], unique=False)
    op.create_table('routers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('firmware', sa.String(), nullable=True),
    sa.Column('adapter_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routers_id'), 'routers', ['id'], unique=False)
    op.create_index(op.f('ix_routers_name'), 'routers', ['name'], unique=False)
    op.create_table('settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=False)
    op.create_table('system_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_logs_id'), 'system_logs', ['id'], unique=False)
    op.create_index(op.f('ix_system_logs_level'), 'system_logs', ['level'], unique=False)
    op.create_index(op.f('ix_system_logs_timestamp'), 'system_logs', ['timestamp'], unique=False)
    op.create_table('device_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mac_address', sa.String(), nullable=True),
    sa.Column('connection_time', sa.DateTime(), nullable=True),
    sa.Column('disconnection_time', sa.DateTime(), nullable=True),
    sa.Column('session_duration', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mac_address'], ['devices.mac_address'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_sessions_connection_time'), 'device_sessions', ['connection_time'], unique=False)
    op.create_index(op.f('ix_device_sessions_id'), 'device_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_device_sessions_mac_address'), 'device_sessions', ['mac_address'], unique=False)
    op.create_table('rssi_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('mac_address', sa.String(), nullable=True),
    sa.Column('raw_rssi', sa.Integer(), nullable=True),
    sa.Column('filtered_rssi', sa.Integer(), nullable=True),
    sa.Column('moving_average', sa.Float(), nullable=True),
    sa.Column('signal_classification', sa.String(), nullable=True),
    sa.Column('distance_classification', sa.String(), nullable=True),
    sa.Column('trend', sa.String(), nullable=True),
    sa.Column('stability_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['mac_address'], ['devices.mac_address'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rssi_history_id'), 'rssi_history', ['id'], unique=False)
    op.create_index(op.f('ix_rssi_history_mac_address'), 'rssi_history', ['mac_address'], unique=False)
    op.create_index(op.f('ix_rssi_history_timestamp'), 'rssi_history', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rssi_history_timestamp'), table_name='rssi_history')
    op.drop_index(op.f('ix_rssi_history_mac_address'), table_name='rssi_history')
    op.drop_index(op.f('ix_rssi_history_id'), table_name='rssi_history')
    op.drop_table('rssi_history')
    op.drop_index(op.f('ix_device_sessions_mac_address'), table_name='device_sessions')
    op.drop_index(op.f('ix_device_sessions_id'), table_name='device_sessions')
    op.drop_index(op.f('ix_device_sessions_connection_time'), table_name='device_sessions')
    op.drop_table('device_sessions')
    op.drop_index(op.f('ix_system_logs_timestamp'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_level'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_id'), table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_routers_name'), table_name='routers')
    op.drop_index(op.f('ix_routers_id'), table_name='routers')
    op.drop_table('routers')
    op.drop_index(op.f('ix_events_timestamp'), table_name='events')
    op.drop_index(op.f('ix_events_mac_address'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_devices_mac_address'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_alerts_timestamp'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_type'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
