import os
import re
from datetime import datetime
from app.services.research.research_manager import get_research_manager

class PublicationEngine:
    def __init__(self):
        self.research_manager = get_research_manager()
        self.publications_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "..", "..", "docs"))
        os.makedirs(self.publications_dir, exist_ok=True)

    def generate_publication(self, exp_id: str, title: str, abstract: str) -> str:
        exp = self.research_manager.get_experiment(exp_id)
        if not exp:
            raise ValueError("Experiment not found")
            
        md = f"""# {title}

**Generated Date**: {datetime.now().strftime('%Y-%m-%d')}
**Experiment ID**: {exp_id}

## Abstract
{abstract}

## Methodology & Experimental Setup
- **Dataset**: {exp.get('dataset')}
- **Model**: {exp.get('model')}
- **Parameters**: 
```json
{exp.get('parameters', {})}
```

## Results & Evaluation Metrics
- **MAE**: {exp.get('metrics', {}).get('MAE', 'N/A')}
- **RMSE**: {exp.get('metrics', {}).get('RMSE', 'N/A')}
- **Accuracy**: {exp.get('metrics', {}).get('Accuracy', 'N/A')}

## Discussion & Future Work
Automatically generated by SignalSense Enterprise Experiment & Research Manager.
"""
        safe_title = re.sub(r'[^a-zA-Z0-9_\-]', '_', title.replace(" ", "_"))
        filename = f"Pub_{safe_title}_{datetime.now().strftime('%Y%m%d%H%M')}.md"
        filepath = os.path.join(self.publications_dir, filename)
        
        with open(filepath, 'w') as f:
            f.write(md)
            
        return filepath

publication_engine = PublicationEngine()

def get_publication_engine() -> PublicationEngine:
    return publication_engine
